### ISSUE TITLE
pydasm module does not have MASK_* attributes

### ISSUE THREAD

**Issue by Moirai7** [kevinkoo001/ropf#2]
I tried to install prerequisites followed by the Readme file and test the randomization function. 

> python orp.py -r test\md5\md5.dll

It shows the pydasm module does not have the attribute 'MASK_MODRM_MOD'. I found out the MASK_MODRM_MOD is in the libdasm.h file as macro definitions. Those definitions are not compiled as a python module. I wonder how you compile the pydasm to use those macro definitions.

Thank you so much!

**Comment by kevinkoo001** [comment]
Hi, `orp.py` is an independent tool. Are you trying to experiment `orp` or `ropf`? 
Anyways, `ropf` also makes use of the `pydasm` module. Have you tried to compile/install "https://github.com/jtpereyda/libdasm"? You may have to install `pydasm`. If there is an undefined symbol, I think it is probably because of the version mismatch.

**Comment by Moirai7** [comment]
Thank you for the prompt reply! 
I have installed pydasm, so it can be imported in the insn.py. The module includes attributes/functions defined in pydasm.c. But macro definitions in the libdasm.h are not included. I think pydasm might be updated so those definitions are removed. I solved the issue by redefined all macros.
Thanks again! This is an interesting project.
